import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'podacast_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'podacast_model.g.dart';

@freezed
abstract class PodacastModel with _$PodacastModel{
  const factory PodacastModel({
    required int id,
    required String title,
    required String description,
    required String coverImage,
    required int followersCount,
    required num rating,
    required int episodesCount,
  })=_PodacastModel;

  factory PodacastModel.fromJson(Map<String,Object?>json)=>_$PodacastModelFromJson(json);
}
