import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'epsiode_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'epsiode_model.g.dart';

@freezed
abstract class EpsiodeModel with _$EpsiodeModel {
  const factory EpsiodeModel({
    required int id,
    required int podcastId,
    required String title,
    required String description,
    required String coverImage,
    required String audioUrl,
    required DateTime publishDate,
    required int plays,
    required int likes,
    required int comments,
  }) = _EpsiodeModel;

  factory EpsiodeModel.fromJson(Map<String, Object?> json) =>
      _$EpsiodeModelFromJson(json);
}
