import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
abstract class UserModel with _$UserModel{
  const factory UserModel({
    required int id,
    required String email,
    required String password,
    required String name,
    required int age,
    required List<int> followedPodcasts,
    required List<int> likes,
  })=_UserModel;

  factory UserModel.fromJson(Map<String,Object?>json)=>_$UserModelFromJson(json);
}
  